#   There isn't a way to create true constants in Python, so please don't modify these in other classes
#   Again: DO NOT MODIFY THESE VARIABLES

#   Base constants:
CONST_BASE_CHANNEL = 1
CONST_BASE_OFFSET = 0
CONST_BASE_ANGLE_START = 160
CONST_BASE_MIN_PWM = 1200
CONST_BASE_MAX_PWM = 9200
CONST_BASE_MAX_ANGLE = 180 # changed from 180
CONST_BASE_SPEED = 10


#   Joint 1 constants:
CONST_JOINT_1_CHANNEL = 2
CONST_JOINT_1_OFFSET = 20 - 98
CONST_JOINT_1_ANGLE_START = 30
CONST_JOINT_1_MIN_PWM = 2700
CONST_JOINT_1_MAX_PWM = 5900
CONST_JOINT_1_MAX_ANGLE = 180
CONST_JOINT_1_SPEED = 10


#   Joint 2 constants:
CONST_JOINT_2_CHANNEL = 3
CONST_JOINT_2_OFFSET = 10
CONST_JOINT_2_ANGLE_START = 50
CONST_JOINT_2_MIN_PWM = 2800
CONST_JOINT_2_MAX_PWM = 7800
CONST_JOINT_2_MAX_ANGLE = 180
CONST_JOINT_2_SPEED = 10

#   Joint 3 constants:
CONST_JOINT_3_CHANNEL = 5
CONST_JOINT_3_OFFSET = 0
CONST_JOINT_3_ANGLE_START = 50
CONST_JOINT_3_MIN_PWM = 3900
CONST_JOINT_3_MAX_PWM = 8100
CONST_JOINT_3_MAX_ANGLE = 180
CONST_JOINT_3_SPEED = 10

#   Gripper constants:
CONST_GRIPPER_CHANNEL = 4
CONST_GRIPPER_OFFSET = 0
CONST_GRIPPER_ANGLE_START = 30
CONST_GRIPPER_MIN_PWM = 2600
CONST_GRIPPER_MAX_PWM = 9200
CONST_GRIPPER_MAX_ANGLE = 180
CONST_GRIPPER_SPEED = 10

ARM_1_LENGTH = 12
ARM_2_LENGTH = 7
